package JFrames;

import Core.Pesquisa;
import Enums.TiposPesquisa;
import Exeption.ExceptionMinimo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

public class PesquisaJFrame extends javax.swing.JFrame{

    private Pesquisa pesquisa;

    public PesquisaJFrame(Pesquisa p){
        this.pesquisa = p;
        initComponents();
        definirTiposPesquisa();
        this.TextBox_input.setEnabled(false);
    }


    private void definirTiposPesquisa(){

        String tipos[] = new String[TiposPesquisa.values().length];
        int cont = 0;
        for (TiposPesquisa t : TiposPesquisa.values()){
            tipos[cont] = t.toString();
            cont++;
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(tipos);
        this.ComboBox_tipoPesquisa.setModel(model);
        this.ComboBox_tipoPesquisa.setSelectedIndex(0);
        this.ComboBox_tipoPesquisa.addActionListener (new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(ComboBox_tipoPesquisa.getSelectedItem().equals(TiposPesquisa.NORMAL.toString())){
                    TextBox_input.setEnabled(false);
                }else if (ComboBox_tipoPesquisa.getSelectedItem().equals
                        (TiposPesquisa.COM_LIMITE_MAXIMO.toString()) ||
                        ComboBox_tipoPesquisa.getSelectedItem().equals
                                (TiposPesquisa.COM_LIMITE_GRAU.toString())){
                    TextBox_input.setEnabled(true);
                }
            }
        });

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TextBox_pesquisa = new javax.swing.JTextField();
        Button_pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBox_tipoPesquisa = new javax.swing.JComboBox<>();
        TextBox_input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_pesquisa = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextBox_pesquisa.setForeground(new java.awt.Color(153, 153, 153));
        TextBox_pesquisa.setText("Pesquisa");
        TextBox_pesquisa.setToolTipText("Pesquisa");
        TextBox_pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextBox_pesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextBox_pesquisaFocusLost(evt);
            }
        });
        TextBox_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox_pesquisaActionPerformed(evt);
            }
        });

        Button_pesquisar.setText("Pesquisar");
        Button_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Button_pesquisarActionPerformed(evt);
                } catch (IOException | ExceptionMinimo e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel1.setText("Motor de pesquisa");

        ComboBox_tipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_tipoPesquisaActionPerformed(evt);
            }
        });

        TextBox_input.setForeground(new java.awt.Color(153, 153, 153));
        TextBox_input.setText("Limite");
        TextBox_input.setToolTipText("Limite");
        TextBox_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextBox_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextBox_inputFocusLost(evt);
            }
        });
        TextBox_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox_inputActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(List_pesquisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup
                                        (javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(79, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup
                                                        (javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ComboBox_tipoPesquisa,
                                                                javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TextBox_input,
                                                                javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap
                                                        (javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                                .addComponent(Button_pesquisar)))
                                .addGap(71, 71, 71))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(TextBox_pesquisa,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup
                                        (javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(TextBox_pesquisa,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(ComboBox_tipoPesquisa,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap
                                                        (javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextBox_input,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(Button_pesquisar)))
                                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void TextBox_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {
        TextBox_pesquisa.setText("Pesquisa");
        TextBox_pesquisa.setForeground(Color.GRAY);
    }

    private void Button_pesquisarActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ExceptionMinimo {

        if(TextBox_pesquisa.getText().equals("") ||
                (TextBox_pesquisa.getForeground() == Color.GRAY &&
                        TextBox_pesquisa.getText().equals("Pesquisa"))
        ){
            JOptionPane.showMessageDialog(null, "Deve de ser introduzido uma pesquisa");
            return;
        }

        String[] resultados = new String[0];

        switch (ComboBox_tipoPesquisa.getSelectedIndex()){
            case 0:
                resultados = pesquisa.pesquisar(TextBox_pesquisa.getText(), TiposPesquisa.NORMAL, -1);
                break;
            case 1:
                try{
                    Double values = Double.parseDouble(TextBox_input.getText());
                    resultados = pesquisa.pesquisar(TextBox_pesquisa.getText(), TiposPesquisa.COM_LIMITE_MAXIMO, values);
                }catch (Exception c){
                    JOptionPane.showMessageDialog(null, "Deve de ser introduzido um valor numérico como limite");
                    return;
                }
                break;
            case 2:
                try{
                    Double values = Double.parseDouble(TextBox_input.getText());
                    resultados = pesquisa.pesquisar(TextBox_pesquisa.getText(), TiposPesquisa.COM_LIMITE_GRAU, values);
                }catch (Exception c){
                    JOptionPane.showMessageDialog(null, "Deve de ser introduzido um valor numérico como limite");
                    return;
                }
                break;
        }
        DefaultListModel modelo = new DefaultListModel();

        for(int i=0; i<resultados.length; i++){
            modelo.addElement(resultados[i]);
        }

        List_pesquisa.setModel(modelo);

        // TODO add your handling code here:
    }

    private void ComboBox_tipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TextBox_inputActionPerformed(java.awt.event.ActionEvent evt) {
        TextBox_pesquisa.setText("Limite");
        TextBox_pesquisa.setForeground(Color.GRAY);
    }

    private void TextBox_pesquisaFocusGained(java.awt.event.FocusEvent evt) {

        if(TextBox_pesquisa.getText().equals("Pesquisa")){
            TextBox_pesquisa.setText("");
            TextBox_pesquisa.setForeground(Color.BLACK);
        }
    }

    private void TextBox_pesquisaFocusLost(java.awt.event.FocusEvent evt) {

        if(TextBox_pesquisa.getText().equals("")){
            TextBox_pesquisa.setText("Pesquisa");
            TextBox_pesquisa.setForeground(Color.GRAY);
        }
    }

    private void TextBox_inputFocusGained(java.awt.event.FocusEvent evt) {

        if(TextBox_input.getText().equals("Limite")){
            TextBox_input.setText("");
            TextBox_input.setForeground(Color.BLACK);
        }
    }

    private void TextBox_inputFocusLost(java.awt.event.FocusEvent evt) {

        if(TextBox_input.getText().equals("")){
            TextBox_input.setText("Limite");
            TextBox_input.setForeground(Color.GRAY);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Button_pesquisar;
    private javax.swing.JComboBox<String> ComboBox_tipoPesquisa;
    private javax.swing.JList<String> List_pesquisa;
    private javax.swing.JTextField TextBox_input;
    private javax.swing.JTextField TextBox_pesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}